{
    'name': 'Sunrise Hotel Management System',
    'version': '1.0',
    'summary': '',
    'category': 'Hotel',
    'author': 'Almustafa',
    'website': '',
    'license': 'LGPL-3',

    'depends': [
        'base',
        'account',
        'account_payment',
        "contacts",   
        "product",    
        "mail",
    ],
    'data': [
    "security/security.xml",
    "security/ir.model.access.csv",
    "data/sequences.xml",
    "views/hotel_room_views.xml",
    "views/hotel_reservation_views.xml",
    "views/hotel_reservation_calendar_view.xml",
    "views/hotel_availability_views.xml",
    "views/hotel_housekeeping_views.xml",
    "views/hotel_event_views.xml",
    "views/hotel_event_booking_calendar_view.xml",
    "views/hotel_event_availability_views.xml",
    "views/res_partner_views.xml",
    "views/menus.xml",
    ],
    'demo': [
        "demo/demo_data.xml",
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
